# Generated by Django 5.1 on 2024-09-02 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_originate_cleared_by_originate_is_completed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='originate',
            old_name='ndc_no',
            new_name='hr_no',
        ),
        migrations.AlterField(
            model_name='originate',
            name='dept',
            field=models.CharField(choices=[('Adm', 'Adm'), ('Operations', 'Operations'), ('ICT', 'ICT'), ('HR', 'HR'), ('Marketing', 'Marketing'), ('Finance', 'Finance'), ('Media', 'Media'), ('Security', 'Security'), ('Planning', 'Planning'), ('Business', 'Business'), ('Sales', 'Sales'), ('BT', 'BT'), ('Engineers', 'Engineers')], max_length=50),
        ),
    ]
