# Generated by Django 5.1 on 2024-09-04 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_originate_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='originate',
            name='is_completed_by_adm',
            field=models.BooleanField(default=False),
        ),
    ]
